# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18171D)
$foreground = rgb(D0CCE7)
$color0 = rgb(403E45)
$color1 = rgb(120E26)
$color2 = rgb(1A0F2B)
$color3 = rgb(431664)
$color4 = rgb(5B1856)
$color5 = rgb(94207C)
$color6 = rgb(5A538C)
$color7 = rgb(B3AED4)
$color8 = rgb(7D7A95)
$color9 = rgb(181332)
$color10 = rgb(231439)
$color11 = rgb(591D86)
$color12 = rgb(792073)
$color13 = rgb(C52BA5)
$color14 = rgb(786EBB)
$color15 = rgb(B3AED4)
