# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0CCE7
background         #18171D
cursor             #797090

active_tab_foreground     #18171D
active_tab_background     #D0CCE7
inactive_tab_foreground   #D0CCE7
inactive_tab_background   #18171D

active_border_color   #D0CCE7
inactive_border_color #18171D
bell_border_color     #120E26

color0      #403E45
color1		#120E26
color2		#1A0F2B
color3		#431664
color4		#5B1856
color5		#94207C
color6		#5A538C
color7		#B3AED4
color8		#7D7A95
color9		#181332
color10		#231439
color11		#591D86
color12		#792073
color13		#C52BA5
color14		#786EBB
color15		#B3AED4
